"""add_legacy_fields

Revision ID: 35dac8232521
Revises: d584c9d2ea2e
Create Date: 2026-07-07 19:44:17.167948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35dac8232521'
down_revision: Union[str, Sequence[str], None] = 'd584c9d2ea2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('galvanic_skin_response', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('stress_index', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'stress_index')
    op.drop_column('sensor_readings', 'galvanic_skin_response')
    # ### end Alembic commands ###
