"""add_data_source_to_sensor_readings

Revision ID: 49dc90f59ae5
Revises: fc02bc217854
Create Date: 2026-08-02 13:23:05.983034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49dc90f59ae5'
down_revision: Union[str, Sequence[str], None] = 'fc02bc217854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('data_source', sa.String(length=50), server_default='unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'data_source')
    # ### end Alembic commands ###
