"""add_google_fit_fields_to_users

Revision ID: 7c190c849a26
Revises: 49dc90f59ae5
Create Date: 2026-08-02 13:35:50.775006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c190c849a26'
down_revision: Union[str, Sequence[str], None] = '49dc90f59ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_fit_refresh_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('google_fit_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('google_fit_last_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_fit_last_sync')
    op.drop_column('users', 'google_fit_connected_at')
    op.drop_column('users', 'google_fit_refresh_token')
    # ### end Alembic commands ###
