"""Initial migration

Revision ID: 9fc14d8130db
Revises: 
Create Date: 2026-07-06 20:50:27.828429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc14d8130db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('device_token_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_device_id'), 'users', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_device_id'), table_name='users')
    op.drop_column('users', 'device_token_hash')
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###
