"""reconcile_schema_drift

Revision ID: d584c9d2ea2e
Revises: 9fc14d8130db
Create Date: 2026-07-07 19:41:21.217118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd584c9d2ea2e'
down_revision: Union[str, Sequence[str], None] = '9fc14d8130db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token_hash')
    # ### end Alembic commands ###
