"""Add practitioner registry and user verification

Revision ID: fc02bc217854
Revises: 35dac8232521
Create Date: 2026-07-31 22:08:28.200263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc02bc217854'
down_revision: Union[str, Sequence[str], None] = '35dac8232521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_practitioners_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('registration_body', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verified_practitioners_registry_id'), 'verified_practitioners_registry', ['id'], unique=False)
    op.create_index(op.f('ix_verified_practitioners_registry_registration_number'), 'verified_practitioners_registry', ['registration_number'], unique=True)
    op.drop_index(op.f('ix_phone_data_id'), table_name='phone_data')
    op.drop_index(op.f('ix_phone_data_user_id'), table_name='phone_data')
    op.drop_table('phone_data')
    op.drop_index(op.f('ix_mental_health_assessments_id'), table_name='mental_health_assessments')
    op.drop_index(op.f('ix_mental_health_assessments_user_id'), table_name='mental_health_assessments')
    op.drop_table('mental_health_assessments')
    op.add_column('users', sa.Column('registration_number', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('registration_body', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('verification_reason', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verified_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_by')
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'verification_reason')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'registration_body')
    op.drop_column('users', 'registration_number')
    op.create_table('mental_health_assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('phone_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('phq9_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phq9_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('combined_risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('combined_risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('agreement', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('cross_validation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommendations_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mental_health_assessments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mental_health_assessments_pkey'))
    )
    op.create_index(op.f('ix_mental_health_assessments_user_id'), 'mental_health_assessments', ['user_id'], unique=False)
    op.create_index(op.f('ix_mental_health_assessments_id'), 'mental_health_assessments', ['id'], unique=False)
    op.create_table('phone_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('steps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity_level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('screen_time_minutes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('screen_state', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('screen_brightness', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('battery_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_charging', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('battery_drain_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('app_usage_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('running_apps_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_app_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('notification_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_sleep_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sleep_quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unique_locations', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_time_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('heart_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('activity_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('screen_time_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sleep_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('social_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mobility_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('battery_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('composite_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('adb_connected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('android_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('phone_data_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('phone_data_pkey'))
    )
    op.create_index(op.f('ix_phone_data_user_id'), 'phone_data', ['user_id'], unique=False)
    op.create_index(op.f('ix_phone_data_id'), 'phone_data', ['id'], unique=False)
    op.drop_index(op.f('ix_verified_practitioners_registry_registration_number'), table_name='verified_practitioners_registry')
    op.drop_index(op.f('ix_verified_practitioners_registry_id'), table_name='verified_practitioners_registry')
    op.drop_table('verified_practitioners_registry')
    # ### end Alembic commands ###
